server:
  port: 8066

spring:
  application:
    name: rsocket-broker-aware-responder-server

io.rsocket.routing.client:
  service-name: rsocket-broker-aware-responder-server
  brokers:
    - host: localhost
      port: 8002

logging:
  level:
    io.rsocket.routing.client: DEBUG