server:
  port: 8065

spring:
  application:
    name: rsocket-broker-aware-requester-server


io.rsocket.routing.client:
  service-name: rsocket-broker-aware-requester-server
  brokers:
    - host: localhost
      port: 8002

logging:
  level:
    io.rsocket.routing.client: INFO