server:
  port: 8062
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
spring:
  application:
    name: responder-server

  rsocket:
    server:
      mapping-path: /rsocket
      transport: websocket
